### PR TITLE
PDD Test Stories

### PR DESCRIPTION
**Pull request by diasdavid**
> WIP

ref: https://github.com/libp2p/interop/issues/1

The first milestone is to get the Transports and The IPFS Bundle Test Stories done. The reasoning is that the Transports are the simplest ones, enough complex to give us a perspective on how to structure these and the IPFS Bundle ones are the ones primarily needed for interop between js-libp2p, go-libp2p and rust-libp2p.

- Qualitative - Test Stories that check feature interoperability and compliance.
  - **Transports** - (priority)
    - Story 1
      - [x] js-libp2p 
      - [ ] go-libp2p
    - Story 2
      - [x] js-libp2p
      - [ ] go-libp2p
    - Story 3
      - [x] js-libp2p
      - [ ] go-libp2p
  - ~~Protocol and Stream Multiplexing~~
  - ~~Identify~~
  - ~~Encrypted Communications~~
  - ~~Peer Routing~~
  - ~~Content Routing~~
  - ~~PubSub~~
  - ~~Circuit Relay~~
  - **The IPFS bundle** - (priority)
    - Story 1
      - [ ] js-libp2p
      - [ ] go-libp2p
    - Story 2
      - [ ] js-libp2p
      - [ ] go-libp2p
    - Story 3
      - [ ] js-libp2p
      - [ ] go-libp2p
    - Story 4
      - [ ] js-libp2p
      - [ ] go-libp2p
    - Story 5
      - [ ] js-libp2p
      - [ ] go-libp2p
   - ...
- Quantitative - Test Stories focused on stress testing the implementations against each other.
  - ~~Thousands of Muxed Streams~~
  - ~~Hundreds of Peer Connections~~

### CODE REVIEW

**Comment by diasdavid** [comment]
**Update on the plans** -- https://github.com/libp2p/interop/issues/1#issuecomment-352382970 Merging this PR for reference and also as it provides an update to the README and an Important note on the status.

**Comment by whyrusleeping** [comment]
@diasdavid could you provide some insight into how these are supposed to be run? Do you want a different program for each actor? or do you want the program to take an argument telling it what to do?

**Comment by diasdavid** [comment]
I've implemented them myself by creating a program per actor, see for example:

- https://github.com/libp2p/js-libp2p/blob/master/pdd/pdd-the-ipfs-bundle--story-1--peer-a.js
- https://github.com/libp2p/js-libp2p/blob/master/pdd/pdd-the-ipfs-bundle--story-1--peer-b.js

or 

- https://github.com/libp2p/js-libp2p/blob/master/pdd/pdd-transport--story-3--peer-a.js
- https://github.com/libp2p/js-libp2p/blob/master/pdd/pdd-transport--story-3--peer-b.js

And my thought was that this way each actor would be well scoped, easy to debug and introspect plus we could pick different actors from different language implementations.

**Comment by whyrusleeping** [comment]
Okay, that seems a bit excessive, especially for the one with five peers doing almost exactly the same thing. But we will see

**Comment by lgierth** [comment]
Any thoughts on using Cucumber as a human-readable test definition format? There's implementations in virtually all languages, and I've had good experiences with it in the past.

**Pull request merged**
